In [1]:
# the build of sentimateanalysis of RNN model
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.shape

(50000, 2)

In [4]:
# the check of null value 
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [5]:
df.drop_duplicates(inplace = True)

In [6]:
df.shape

(49582, 2)

In [7]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### PRE-PROCESSING

# 1.convertion of lowercase

In [8]:
df["review"] = df["review"].str.lower()

### 2.remove the URL

In [9]:
# THe of regex lib 
import regex as re
def remove_urls(text):
    text = re.sub(r"http\S+","",text) #(pattern,replace,text)
    return text
df["review"] = df["review"].apply(remove_urls)

## 3.remove punctuater

In [10]:
def remove_urls(text):
    text = re.sub(r"http\S+" , "", text)  # (pattern, repl, string) eg - https://www.google.com
    return text
    
df["review"] = df["review"].apply(remove_urls)

## 4. remove HTML

In [11]:
def remove_html(text):
    text = re.sub(r"<.*?>","",text)
    return text

df["review"] = df["review"].apply(remove_html)

# 5. Remove the stopwords

In [12]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Shivam\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Shivam\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Shivam\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
from nltk.tokenize import  word_tokenize
from nltk.corpus import stopwords # the find of language of stop_words 

def remove_stopwords(text):
    token = word_tokenize(text)
    stop_word = stopwords.words("english")

    for word in token:
        if word in stop_word:
            text = text.replace(word,"")
    return text
df["review"] = df["review"].apply(remove_stopwords)

In [14]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode 'll  h...  positive
1   wderful ltle producti.  filming technique   u...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly 's  fmly   lttle boy (jke) thks 's  zom...  negative
4  petter mttei's "love   time  mey"   vully stun...  positive

## 6. Stemming

In [15]:
# runing->run
# playing->play

from nltk.stem import PorterStemmer

In [16]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)
    return "".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [17]:
df.head()

                                              review sentiment
0  erevewntedwtchg1ozepod'llhook.yrght,exctlihppe...  positive
1  wderltleproducti.filmtechniquunssuming-old-tim...  positive
2  thoughtthwderwyspendtmeohotsummerweekend,sttng...  positive
3  bsclli'sfmlilttleboy(jke)thk'szombcloset&prent...  negative
4  pettermttei's``lovetimemey''vullistunngfilmwtc...  positive

## 7.Encoding

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

print(le.classes_)
print(df["sentiment"].value_counts())

['negative' 'positive']
sentiment
1    24884
0    24698
Name: count, dtype: int64

In [19]:
y = df["sentiment"]

In [20]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int32

## 8. vectorization

In [21]:
df.head()

                                              review  sentiment
0  erevewntedwtchg1ozepod'llhook.yrght,exctlihppe...          1
1  wderltleproducti.filmtechniquunssuming-old-tim...          1
2  thoughtthwderwyspendtmeohotsummerweekend,sttng...          1
3  bsclli'sfmlilttleboy(jke)thk'szombcloset&prent...          0
4  pettermttei's``lovetimemey''vullistunngfilmwtc...          1

In [22]:
# recreate of TF-idf 
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

In [23]:
print(X)

  (0, 4452)	0.23780377766194746
  (0, 3183)	0.29240741914836405
  (0, 2022)	0.4703665942925332
  (0, 449)	0.30491122882574406
  (0, 3086)	0.32018031466757263
  (0, 4121)	0.313281434337259
  (0, 558)	0.1725586032420872
  (0, 4917)	0.3002454772459519
  (0, 4730)	0.25985309101341003
  (0, 385)	0.2304519518162591
  (0, 2277)	0.32018031466757263
  (1, 2645)	0.5324064350016976
  (1, 4324)	0.5821854770377085
  (1, 844)	0.6144944737710494
  (2, 4224)	0.3618344376059429
  (2, 4787)	0.4770155608270036
  (2, 3390)	0.521476456482965
  (2, 4002)	0.6079426780752117
  (3, 329)	0.4385324307730247
  (3, 1732)	0.5931821979962076
  (3, 4242)	0.39216336983792616
  (3, 2642)	0.33588310479870304
  (3, 1276)	0.4349880669729179
  (4, 2246)	1.0
  (5, 734)	0.7053660308159277
  :	:
  (49576, 8)	0.17722275648797559
  (49576, 2023)	0.2518137598550438
  (49576, 4239)	0.30826892885258145
  (49576, 1308)	0.2990687033619175
  (49576, 892)	0.348747750404372
  (49576, 467)	0.3411941547407117
  (49576, 4548)	0.40417541394714923
  (49576, 2993)	0.3871401986387105
  (49576, 4146)	0.4116264809524104
  (49577, 8)	0.30258378301548394
  (49577, 4572)	0.5225541487694976
  (49577, 1942)	0.4807471479006947
  (49577, 4255)	0.6358163222544478
  (49578, 4452)	0.42246000298406683
  (49578, 172)	0.4459341379128165
  (49578, 183)	0.5593980792959198
  (49578, 174)	0.5565465653498288
  (49579, 3815)	0.5941130571222174
  (49579, 3600)	0.5510886427994544
  (49579, 517)	0.5859445222325643
  (49580, 4847)	1.0
  (49581, 1238)	0.44251039952969734
  (49581, 4643)	0.4085663963009255
  (49581, 2235)	0.48665958874855103
  (49581, 1950)	0.632787871881908

### Dataset & Data Loader

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size = 0.2,random_state = 42,
    stratify = y
)

In [25]:
X_train.shape

(39665, 5000)

In [26]:
X_test.shape

(9917, 5000)

In [27]:
import torch
from torch.utils.data import TensorDataset , DataLoader

In [28]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [29]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(), ## the this fnx authomatically convert of data is tensor
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float() # the pandas data is convert of pandas of numpy data 
    
)

In [30]:
# the create of dataloader

train_loader = DataLoader(train_set,shuffle = True , batch_size = 64)
test_loader = DataLoader(test_set,shuffle = False , batch_size = 64)

## Build of RNN

In [31]:
import torch.nn as nn
import torch.optim as optim

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0) 
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [32]:
# model 
input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

### TRAINING PROCESS

In [33]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction
        
        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.586185097694397
epoch = 2/10 and loss = 0.5206407904624939
epoch = 3/10 and loss = 0.6826716065406799
epoch = 4/10 and loss = 0.5695977210998535
epoch = 5/10 and loss = 0.5051842927932739
epoch = 6/10 and loss = 0.4855178892612457
epoch = 7/10 and loss = 0.5258573889732361
epoch = 8/10 and loss = 0.4517582952976227
epoch = 9/10 and loss = 0.4685725271701813
epoch = 10/10 and loss = 0.5040952563285828

## Evaluetion

In [34]:
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0
    
    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 67.33891297771504

In [35]:
import sys
print(sys.executable)

C:\Users\Shivam\anaconda3\python.exe

In [36]:
import torch
import sklearn
import numpy

print("PyTorch:", torch.__version__)
print("Sklearn:", sklearn.__version__)
print("NumPy:", numpy.__version__)

PyTorch: 2.5.1
Sklearn: 1.5.1
NumPy: 1.26.4

In [37]:
print("Dataset:", df.shape)
print("Train:", X_train.shape)
print("Test:", X_test.shape)
print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("Sklearn:", sklearn.__version__)

Dataset: (49582, 2)
Train: (39665, 5000)
Test: (9917, 5000)
Python: C:\Users\Shivam\anaconda3\python.exe
PyTorch: 2.5.1
Sklearn: 1.5.1